# Generated by Django 3.2.8 on 2021-12-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('Заказ в прогрессе', 'Заказ в обработке'), ('Заказ готов', 'Заказ готов'), ('Заказ завершены', 'Заказ получен пользователем')], default='Новый заказ', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
