# Generated by Django 3.2.8 on 2021-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Оплата в процессе подтвержения'), ('Заказ в прогрессе', 'Оплата подтверждена'), ('Заказ готов', 'Заказ готов'), ('Заказ завершены', 'Заказ получен пользователем')], default='Новый заказ', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
