# Generated by Django 3.2.8 on 2021-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Product', verbose_name='Добавленный товар'),
        ),
    ]
