# Generated by Django 3.2.8 on 2021-10-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
