# Generated by Django 3.2.8 on 2021-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплата в процессе подтвержения', 'Оплата в процессе подтвержения'), ('Оплата подтверждена', 'Оплата подтверждена'), ('Заказ готов', 'Заказ готов'), ('Заказ завершен', 'Заказ получен пользователем')], default='Оплата в процессе подтвержения', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
