# Generated by Django 3.2.8 on 2021-11-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211128_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='size',
        ),
    ]
