# Generated by Django 3.2.8 on 2021-10-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211025_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
