# Generated by Django 3.2.8 on 2021-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211029_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
