# Generated by Django 3.2.8 on 2021-11-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211129_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.colorfield', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sizefield', verbose_name='Цвет товара'),
        ),
    ]
