# Generated by Django 3.2.8 on 2021-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_imagegallery_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
