# Generated by Django 3.2.8 on 2021-10-29 19:07

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function),
        ),
    ]
